### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by compwron** [robertjlooby/elm-koans#9]
This is super great and it really helped me get a feel for elm. I'm wondering about the correct answer to one of the UnionTypes koans. Is there a place where I can see what the expected answers are?

https://github.com/compwron/elm-koans/blob/d1eead258ce71372fe16b873f2ad2a105d72215b/src/Koans/AboutUnionTypes.elm#L34

**Comment by robertjlooby** [comment]
Nice! I'm glad it could help you get a feel for it.

As for that test, ya I don't know what I was going for there lol. I think I was trying to show "hey look this compiles even though one is a `Strand` and one is a `Base` because they're both `DNA`". To be honest that whole suite isn't my favorite and could probably use another look. I'll leave this issue open to remind myself to take another pass and see if I can come up with something a little clearer.

Thanks for the feedback! :smile:

**Comment by compwron** [comment]
:)

**Comment by dennisreimann** [comment]
I also wanted to chime in as I just finished the koans - thanks for all of those! I like that I got to learn a little bit about elm-test too! :)

**Comment by robertjlooby** [comment]
I ended up putting a comment in there (https://github.com/robertjlooby/elm-koans/pull/25) which should make this one less confusing.
